### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by xgerhard** [xgerhard/DestinyCommand#1]
- [x] Request parser

- Parse variables: user, channel, defaultconsole, token, platform, query
- Parse Nightbot headers: user, channel, role
- Parse the query, examples:

> !destiny kd xgerhard xbox
!destiny kd;wl xgerhard,notxgerhard
!destiny wl-kd notxgerhard;xgerhard xbox
!destiny d1 kd xgerhard

- [x] Token generator (Channel settings are linked to this token)
- [ ] User - account relation, people need to be able to link their Bungie account. 
- [ ] Output formatter, plain-text but also make a JSON output available for future integatrions
- [ ] Error handling, log exceptions, output exceptions as user friendly text

- [x] Installation guide
- [ ] Installation code generator

**Comment by xgerhard** [comment]
Meh, not happy with the current code base. While the API works fine it's most likely going to be rewritten totally.
